name: Run test
on:
  - workflow_dispatch
  - push

env:
  PATH_CACHE: /tmp/.buildx-cache
  IMAGE_NAME: ciimage

jobs:
  Run-CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Enable ci cache
        id: cache_ci
        uses: actions/cache@v3
        with:
          path: ${{ env.PATH_CACHE }}
          key: ${{ env.IMAGE_NAME }}
          restore-keys: ${{ env.IMAGE_NAME }}

      - name: Build ci image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=local,src=${{ env.PATH_CACHE }}
          cache-to: type=local,dest=${{ env.PATH_CACHE }},mode=max
          file: docker/Dockerfile.ci
          context: .

      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ env.PATH_CACHE }}
          mv ${{ env.PATH_CACHE }}-new ${{ env.PATH_CACHE }}
